### ISSUE TITLE
Make documentaion on hover optional

### ISSUE THREAD

**Issue by w3bsite** [forestxieCode/naive-ui-helper#2]
Hi first of all thank you for the effort you made on this extension I really liked the experience it brings specially the kebab case suggestion. 
it's great thank you really, I wanted to ask is it possible to disable the document link on hover? the reason is I use it along side atomic css extensions like windy and it does not look very well together.

**Comment by forestSenn** [comment]
Thank you for your suggestion. I have been busy recently getting married and the house has not been updated much. I will optimize it after some time

**Comment by forestSenn** [comment]
publishing
